[tool.poetry]
name = "TISC-2021"
version = "0.1.0"
description = ""
authors = ["winstxnhdw <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.12"
scipy = "^1.11.3"
matplotlib = "^3.8.0"
